"""
scenarios/debrief_detector.py — AI Debrief Detector
=====================================================
KEY MODULE: Analyses the session transcript to determine whether a
human-led debriefing was conducted at the end of the session.

Context
-------
Real audio recordings of simulation sessions contain TWO phases:
  Phase 1: The clinical scenario (team managing the patient)
  Phase 2: The post-scenario debriefing (instructor/team discussion)

When audio extraction is live, the pipeline will produce both phases
as segments in the JSON. Until then, synthesised session data mimics
this format via the 'debrief_segments' field.

If no meaningful human debrief is detected (or if the admin has configured
the AI debrief to run), the system:
  1. Takes the NarrativeEngine output (already generated by the main pipeline)
  2. Converts it to speech via VoiceNarrator
  3. Returns the audio URL + text so the frontend can play it

Debrief Quality Scoring
-----------------------
  0     : No debrief at all (debrief_segments empty or absent)
  1–39  : Minimal (< 2 instructor turns, no structured elements)
  40–69 : Partial (some discussion but no clear what-went-well / improvement)
  70–100: Adequate (structured debrief with both positive and improvement elements)
"""

from __future__ import annotations

import logging
import re
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

# Keywords that indicate a structured debrief element
_POSITIVE_KWS  = ["well", "good", "great", "excellent", "correct", "right", "strong", "strength"]
_IMPROVEMENT_KWS = ["improve", "could", "should", "missed", "delayed", "forgot", "better", "next time", "work on"]
_QUESTION_KWS    = ["what", "how", "why", "when", "did you", "can you", "could you"]
_CLOSURE_KWS     = ["summary", "conclude", "wrap up", "final", "closing", "thank you", "well done", "debrief complete"]

# Roles that indicate an instructor is speaking
_INSTRUCTOR_ROLES = {"instructor", "facilitator", "debriefer", "educator", "faculty"}


class DebriefDetector:
    """
    Analyse debrief_segments from a session JSON to determine:
      - Whether a human debrief occurred
      - Quality score (0–100)
      - Recommendation: 'ai_full' | 'ai_supplement' | 'human_adequate'

    Usage
    -----
    detector = DebriefDetector()

    result = detector.analyse(session_data)
    # result = {
    #   "human_debrief_present":  bool,
    #   "debrief_quality_score":  0–100,
    #   "recommendation":         "ai_full" | "ai_supplement" | "human_adequate",
    #   "quality_label":          "Absent" | "Minimal" | "Partial" | "Adequate",
    #   "instructor_turns":       int,
    #   "has_positive_feedback":  bool,
    #   "has_improvement_points": bool,
    #   "has_questions":          bool,
    # }
    """

    # ── Public API ────────────────────────────────────────────────────────────

    def analyse(self, session_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Analyse the debrief_segments in session_data.

        The session JSON should have:
          "debrief_segments": [...]    — list of segment dicts (may be empty)
          "human_debrief_present": bool  — explicit flag (optional, inferred if absent)
          "human_debrief_quality": str   — "absent"|"minimal"|"partial"|"adequate" (optional)
        """
        debrief_segs = session_data.get("debrief_segments", [])
        explicit_present = session_data.get("human_debrief_present")

        if not debrief_segs:
            # No debrief segments at all
            return self._build_result(
                present=False,
                quality_score=0,
                instructor_turns=0,
                has_positive=False,
                has_improvement=False,
                has_questions=False,
            )

        # Parse quality from segments
        quality_score, details = self._score_debrief(debrief_segs)

        # Honour explicit flag if provided
        present = bool(debrief_segs) if explicit_present is None else bool(explicit_present)

        return self._build_result(
            present            = present,
            quality_score      = quality_score,
            instructor_turns   = details["instructor_turns"],
            has_positive       = details["has_positive"],
            has_improvement    = details["has_improvement"],
            has_questions      = details["has_questions"],
        )

    def should_ai_debrief(
        self,
        detector_result:          Dict[str, Any],
        ai_debrief_flag_enabled:  bool,
    ) -> bool:
        """
        Return True if the AI should generate and speak the debriefing.

        Rules:
          1. If admin flag 'ai_debrief_speech_enabled' is False → never AI debrief.
          2. If no human debrief present → always AI debrief (if flag True).
          3. If human debrief minimal (score < 40) → AI debrief to supplement.
          4. If human debrief adequate (score ≥ 70) → no AI debrief.
        """
        if not ai_debrief_flag_enabled:
            return False
        recommendation = detector_result.get("recommendation", "human_adequate")
        return recommendation in ("ai_full", "ai_supplement")

    # ── Internal scoring ──────────────────────────────────────────────────────

    def _score_debrief(
        self, segments: List[Dict[str, Any]]
    ) -> Tuple[int, dict]:
        """
        Score the quality of a human debrief from its segments.
        Returns (score 0–100, details dict).
        """
        instructor_turns = 0
        team_turns       = 0
        has_positive     = False
        has_improvement  = False
        has_questions    = False
        has_closure      = False

        for seg in segments:
            role = seg.get("role", "").lower()
            text = seg.get("text", "").lower()

            is_instructor = (
                role in _INSTRUCTOR_ROLES
                or seg.get("speaker", "").lower() in _INSTRUCTOR_ROLES
            )

            if is_instructor:
                instructor_turns += 1
            else:
                team_turns += 1

            if any(kw in text for kw in _POSITIVE_KWS):
                has_positive = True
            if any(kw in text for kw in _IMPROVEMENT_KWS):
                has_improvement = True
            if any(kw in text for kw in _QUESTION_KWS):
                has_questions = True
            if any(kw in text for kw in _CLOSURE_KWS):
                has_closure = True

        # Score calculation
        score = 0
        if instructor_turns >= 1:
            score += 20  # instructor participated
        if instructor_turns >= 3:
            score += 10  # meaningful instructor engagement
        if team_turns >= 2:
            score += 10  # team participated
        if has_positive:
            score += 20  # positive feedback given
        if has_improvement:
            score += 20  # improvement points raised
        if has_questions:
            score += 10  # reflective questions asked
        if has_closure:
            score += 10  # debrief was formally closed

        return min(score, 100), {
            "instructor_turns": instructor_turns,
            "has_positive":     has_positive,
            "has_improvement":  has_improvement,
            "has_questions":    has_questions,
        }

    def _build_result(
        self,
        present:          bool,
        quality_score:    int,
        instructor_turns: int,
        has_positive:     bool,
        has_improvement:  bool,
        has_questions:    bool,
    ) -> Dict[str, Any]:
        if not present or quality_score == 0:
            quality_label  = "Absent"
            recommendation = "ai_full"
        elif quality_score < 40:
            quality_label  = "Minimal"
            recommendation = "ai_supplement"
        elif quality_score < 70:
            quality_label  = "Partial"
            recommendation = "ai_supplement"
        else:
            quality_label  = "Adequate"
            recommendation = "human_adequate"

        return {
            "human_debrief_present":  present,
            "debrief_quality_score":  quality_score,
            "recommendation":         recommendation,
            "quality_label":          quality_label,
            "instructor_turns":       instructor_turns,
            "has_positive_feedback":  has_positive,
            "has_improvement_points": has_improvement,
            "has_questions":          has_questions,
        }


# ── Convenience function ──────────────────────────────────────────────────────

def check_and_prepare_ai_debrief(
    session_data:             Dict[str, Any],
    narrative_text:           str,
    overall_score:            float,
    grade:                    str,
    ai_debrief_flag_enabled:  bool,
    voice_narrator=None,
    use_server_tts:           bool = False,
) -> Dict[str, Any]:
    """
    One-stop helper used by server.py after the pipeline completes.

    Returns:
    {
      "ai_debrief_needed":   bool,
      "detector_result":     dict,
      "debrief_audio":       dict | None,   # from VoiceNarrator
      "debrief_text":        str | None,    # text for browser TTS if no server audio
    }
    """
    detector = DebriefDetector()
    det_result = detector.analyse(session_data)
    ai_needed  = detector.should_ai_debrief(det_result, ai_debrief_flag_enabled)

    debrief_audio = None
    debrief_text  = None

    if ai_needed and narrative_text:
        if voice_narrator is not None:
            debrief_audio = voice_narrator.speak_debrief_summary(
                narrative_text = narrative_text,
                score          = overall_score,
                grade          = grade,
                use_server_tts = use_server_tts,
            )
            debrief_text = debrief_audio.get("text")
        else:
            debrief_text = narrative_text

    return {
        "ai_debrief_needed": ai_needed,
        "detector_result":   det_result,
        "debrief_audio":     debrief_audio,
        "debrief_text":      debrief_text,
    }
